import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { css } from '@styles/css'
import Steps from '@/app/components/Steps'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={css({ backgroundColor: '#EFF5FF' }, inter.style)}>
        <div className={css({
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100%',
          backgroundImage: 'url(../../public/head-background.svg)',
          backgroundSize: '100%',
          backgroundRepeat: 'no-repeat',
        })}
        >
          <Steps />
          {children}
        </div>
      </body>
    </html>
  )
}
